# Generated by Django 4.2.9 on 2024-05-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
