# Generated by Django 4.2.9 on 2024-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='restock_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='restock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='restock_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
