# Generated by Django 4.2.9 on 2024-05-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_table_id_alter_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
