<!--Navigator-->
<nav class="navbar">
	<div class="navbar-container container">
		<input type="checkbox" name="" id="">
		<div class="hamburger-lines">
			<span class="line line1"></span>
			<span class="line line2"></span>
			<span class="line line3"></span>
		</div>
		<ul class="menu-items">
			<li><a href="index.php">Index</a></b></li>
			<li><a href="about.php">About Us</a></li>
			<li><a href="product.php">Our Cars</a></li>
			<li><a href="payment.php">Payment</a></li>
			<li><a href="enhancements.php">Enhancements</a></li>
			<li><a href="enhancements2.php">Enhancements 2</a></li>
			<li><a href="manager.php">Management</a></li>
		</ul>
		<h1 class="logo">FOO <span class="logo-highlight">MOTORS</span></h1>
	</div>
</nav>